apiVersion: v1
kind: Service
metadata:
  labels:
    app: pet-clinic
  name: pet-clinic
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: pet-clinic
